-- DDL generated by Postico 2.0
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "T_USER" (
    "memberID" integer PRIMARY KEY,
    name text NOT NULL,
    age integer NOT NULL,
    type text NOT NULL,
    "dataRegisterTime" date NOT NULL,
    "dataUpdateTime" date NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "PETHOTEL_memberManagement_pkey" ON "T_USER"("memberID" int4_ops);
