--pet_hotel.sql
CREATE TABLE public."T_CLIENT" (
    CLIENT_CODE character(5) PRIMARY KEY,
    CLIENT_NAME character varying,
    CLIENT_TEL character varying,
    PET_CODE1 character(5),
    PET_CODE2 character(5),
    PET_CODE3 character(5),
    CONSTRAINT unique_client_code UNIQUE (CLIENT_CODE)
);
CREATE TABLE public."T_EMPLOYEE" (
    EMPLOYEE_CODE character(5) PRIMARY KEY,
    EMPLOYEE_NAME character varying,
    EMPLOYEE_SKILL character varying,
    EMPLOYEE_MAX integer,
    EMPLOYEE_COST integer
);

CREATE TABLE public."T_PET" (
    PET_CODE character(5) PRIMARY KEY,
    PET_NAME character varying,
    PET_TYPE character varying,
    CLIENT_CODE character(5),
    PET_AGE integer,
    PET_HEALTH character,
    CONSTRAINT fk_client FOREIGN KEY (CLIENT_CODE) REFERENCES public."T_CLIENT" (CLIENT_CODE)
);
CREATE TABLE public."T_ORDER" (
    ORDER_CODE character(5) PRIMARY KEY,
    ORDER_CHECKIN date,
    ORDER_CHECKOUT date,
    PET_CODE character(5),
    EMPLOYEE_CODE character(5),
    ORDER_COST integer
);
CREATE TABLE public."T_SCHEDULE" (
    "EMPLOYEE_CODE" INTEGER NOT NULL,
    "DAY_1" CHARACTER VARYING(1) NOT NULL,
    "DAY_2" CHARACTER VARYING(1) NOT NULL,
    "DAY_3" CHARACTER VARYING(1) NOT NULL,
    "DAY_4" CHARACTER VARYING(1) NOT NULL,
    "DAY_5" CHARACTER VARYING(1) NOT NULL,
    "DAY_6" CHARACTER VARYING(1) NOT NULL,
    "DAY_7" CHARACTER VARYING(1) NOT NULL,
    "DAY_8" CHARACTER VARYING(1) NOT NULL,
    "DAY_9" CHARACTER VARYING(1) NOT NULL,
    "DAY_10" CHARACTER VARYING(1) NOT NULL,
    "DAY_11" CHARACTER VARYING(1) NOT NULL,
    "DAY_12" CHARACTER VARYING(1) NOT NULL,
    "DAY_13" CHARACTER VARYING(1) NOT NULL,
    "DAY_14" CHARACTER VARYING(1) NOT NULL,
    "DAY_15" CHARACTER VARYING(1) NOT NULL,
    "DAY_16" CHARACTER VARYING(1) NOT NULL,
    "DAY_17" CHARACTER VARYING(1) NOT NULL,
    "DAY_18" CHARACTER VARYING(1) NOT NULL,
    "DAY_19" CHARACTER VARYING(1) NOT NULL,
    "DAY_20" CHARACTER VARYING(1) NOT NULL,
    "DAY_21" CHARACTER VARYING(1) NOT NULL,
    "DAY_22" CHARACTER VARYING(1) NOT NULL,
    "DAY_23" CHARACTER VARYING(1) NOT NULL,
    "DAY_24" CHARACTER VARYING(1) NOT NULL,
    "DAY_25" CHARACTER VARYING(1) NOT NULL,
    "DAY_26" CHARACTER VARYING(1) NOT NULL,
    "DAY_27" CHARACTER VARYING(1) NOT NULL,
    "DAY_28" CHARACTER VARYING(1) NOT NULL,
    "DAY_29" CHARACTER VARYING(1) NOT NULL,
    "DAY_30" CHARACTER VARYING(1) NOT NULL,
    "DAY_31" CHARACTER VARYING(1) NOT NULL
);

--注：部分数据通过csv文件import

insert into public."T_EMPLOYEE" (EMPLOYEE_CODE,EMPLOYEE_NAME,EMPLOYEE_SKILL,EMPLOYEE_MAX,EMPLOYEE_COST)
values('8', 'John', '3', 5, 2500);

ALTER TABLE public."T_EMPLOYEE"
ALTER COLUMN EMPLOYEE_SKILL TYPE integer using (EMPLOYEE_SKILL::integer);
