--pet_hotel_select.sql
-- INNER JOIN 
SELECT *
FROM public."T_CLIENT"
INNER JOIN public."T_ORDER" 
ON public."T_CLIENT".CLIENT_CODE = public."T_ORDER".CLIENT_CODE;

-- LEFT JOIN 左连结
SELECT *
FROM public."T_CLIENT"
LEFT JOIN public."T_ORDER" 
ON public."T_CLIENT".CLIENT_CODE = public."T_ORDER".CLIENT_CODE;


-- RIGHT JOIN 右连结
SELECT *
FROM public."T_CLIENT"
RIGHT JOIN public."T_ORDER" 
ON public."T_CLIENT".CLIENT_CODE = public."T_ORDER".CLIENT_CODE;


-- FULL OUTER JOIN 
SELECT *
FROM public."T_CLIENT"
FULL OUTER JOIN public."T_ORDER" 
ON public."T_CLIENT".CLIENT_CODE = public."T_ORDER".CLIENT_CODE;


-- GROUP BY 
SELECT CLIENT_CODE, COUNT(*) as ORDER_COUNT
FROM public."T_ORDER"
GROUP BY CLIENT_CODE;
