@startuml PetHotelSystem

skinparam monochrome true

package "PETHOTEL" <<rectangle>> {
  package "User" <<rectangle>> {
    ' テーブル
    entity "userinfo" {
      + user_id [PK] : integer
      ==
      lastname : character varying
      firstname : character varying
      birthday : character varying
      gender : character varying
      company : character varying
      city : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "pet" {
      + pet_id [PK] : integer
      ==
      user_id [FK] : character varying
      pet_name : character varying
      pet_species : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "login" {
      + user_id [PK] : integer
      ==
      mail : character varying
      password : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "login_event" {
      + user_id [PK] : integer
      + login_datetime [PK] : timestamp without time zone
      ==
      logout_datetime : timestamp without time zone
    }

    ' リレーション
    userinfo ||--|| login
    userinfo --|{ pet
    login --|{ login_event
  }

  package "RECORD" <<rectangle>>{
    ' テーブル
    entity "checkin_event"{
      + checkin_event_id [PK] : integer
      ==
      user_id [FK] : integer
      pet_id [FK] : integer
      room_no : integer
      checkin_date  : timestamp without time zone
      create_datetime : timestamp without time zone
    }
    entity "checkout_event"{
      + checkout_event_id [PK] : integer
      ==
      checkin_event_id [FK] : integer
      create_datetime : timestamp without time zone
    }
    entity "booking_event"{
      + booking_event_id [PK] : integer
      ==
      user_id [FK] : integer
      pet_id [FK] : integer
      room_no : integer
      reservation_checkin_date : timestamp without time zone
      reservation_checkout_date : timestamp without time zone
      create_datetime : timestamp without time zone
    }
    entity "booking_cancel_event"{
      + booking_cancel_event_id [PK] : integer
      ==
      booking_event_id [FK] : integer
      create_datetime : timestamp without time zone
    }

  }


  ' リレーション
  userinfo --|{ checkin_event
  userinfo --|{ checkout_event
  userinfo --|{ booking_event
  userinfo --|{ booking_cancel_event

}
@enduml